#!/usr/bin/python3
import sys

if 'PYFILE' not in os.environ:
    sys.stderr.write("Error: PYFILE environment variable not set.\n")
    sys.exit(1)

pyfile = os.environ['PYFILE']
output_file = pyfile + 'c'

try:
    with open(pyfile, 'r') as file:
        code = compile(file.read(), pyfile, 'exec')
        with open(output_file, 'wb') as output:
            output.write(code.co_code)
except FileNotFoundError:
    sys.stderr.write(f"Error: File {pyfile} not found.\n")
    sys.exit(1)

print(f"Compiling {pyfile} ...")
